[context."master".environment]
  VUE_APP_ATLAS_GRAPHQL_ENDPOINT = "https://explorehomer-atlas.scaife-viewer.org/graphql/"
[context."feature/latest-packages".environment]
  VUE_APP_ATLAS_GRAPHQL_ENDPOINT = "https://explorehomer-feature-at-wthmih.herokuapp.com/graphql/"
