[context."master".environment]
  VUE_APP_ATLAS_GRAPHQL_ENDPOINT = "https://explorehomer-atlas.scaife-viewer.org/graphql/"
[context."expand-hmt-content".environment]
  VUE_APP_ATLAS_GRAPHQL_ENDPOINT = "https://explorehomer-task-expan-b7cqmf.herokuapp.com/graphql/"
