[context."master".environment]
  VUE_APP_ATLAS_GRAPHQL_ENDPOINT = "https://explorehomer-atlas.scaife-viewer.org/graphql/"
[context."feature/toc-widget".environment]
  VUE_APP_ATLAS_GRAPHQL_ENDPOINT = "https://explorehomer-feature-to-c6d9si.herokuapp.com/graphql/"
